# 各種レイヤの実装
* ここでは、各種レイヤを実装する。
* 実装できたら1データを入力して妥当な結果が出力されることを確認する。

In [1]:
import numpy as np

## 加算レイヤの実装

### [演習]
* 以下の加算レイヤクラスを完成させましょう

In [2]:
class AddLayer:
    def __init__(self):
        pass # 何もしない
        
    def forward(self, x, y):
        return x+y
    
    def backward(self, dout):
        """
        dout : float, 上流(出力)側の勾配
        """
        dLdx = dout
        dLdy = dout
        return dLdx, dLdy

In [3]:
al = AddLayer()
x = np.array([1])
y = np.array([2])
dout = np.array([5])
print("forward=", al.forward(x, y))
dLdx , dLdy = al.backward(dout)
print("dLdx=", dLdx)
print("dLdy=", dLdy)

forward= [3]
dLdx= [5]
dLdy= [5]


## 乗算レイヤの実装

### [演習]
* 以下の乗算レイヤクラスを完成させましょう

In [4]:
class MultiLayer:
    def __init__(self):
        self.x = None
        self.y = None
        
    def forward(self, x, y):
        self.x = x #記憶しておく
        self.y = y #記憶しておく
        return x*y
    
    def backward(self, dout):
        """
        dout : float, 上流(出力)側の勾配
        """        
        dLdx = dout * self.y
        dLdy = dout * self.x
        return dLdx, dLdy

In [5]:
ml = MultiLayer()
x = np.array([1])
y = np.array([2])
dout = np.array([5])
print("forward=", ml.forward(x, y))
dLdx , dLdy = ml.backward(dout)
print("dLdx=", dLdx)
print("dLdy=", dLdy)

forward= [2]
dLdx= [10]
dLdy= [5]


## ReLUレイヤの実装

### [演習]
* 以下のReLUレイヤクラスを完成させましょう

In [19]:
# ヒント
x = np.array([[-1, 1],
              [ 0, 2]])
mask = (x <= 0)
print(mask)
print()

y = x
z = x.copy()
print("id of x=", id(x))
print("id of y=", id(y))
print("id of z=", id(z))
print()

z[mask] = 0
print(z)
print(x)
print()

y[mask] = 0
print(y)
print(x)
print()


[[ True False]
 [ True False]]

id of x= 1967392409600
id of y= 1967392409600
id of z= 1967393015328

[[0 1]
 [0 2]]
[[-1  1]
 [ 0  2]]

[[0 1]
 [0 2]]
[[0 1]
 [0 2]]



array([[False,  True],
       [False,  True]])

In [27]:
class ReLU:
    def __init__(self):
        self.mask = None
        
    def forward(self, x):
        self.mask = (x<=0)
        out = x.copy() #参照渡しではなく複製する
        out[self.mask] = 0
        return out
    
    def backward(self, dout):
        """
        dout : float, 上流(出力)側の勾配
        """        
        dout[self.mask] = 0
        dLdx = dout
        return dLdx

In [28]:
rl = ReLU()

x = np.array([-1])
dout = np.array([3])
print("forward=", rl.forward(x))
dLdx = rl.backward(dout)
print("dLdx=", dLdx)
print()

x = np.array([0])
dout = np.array([3])
print("forward=", rl.forward(x))
dLdx = rl.backward(dout)
print("dLdx=", dLdx)
print()

x = np.array([1])
dout = np.array([3])
print("forward=", rl.forward(x))
dLdx = rl.backward(dout)
print("dLdx=", dLdx)

forward= [0]
dLdx= [0]

forward= [0]
dLdx= [0]

forward= [1]
dLdx= [3]


In [22]:
x = np.array([0])
rl.forward(x)

array([0])

## Sigmoidレイヤの実装

### [演習]
* 以下のSigmoidレイヤクラスを完成させましょう

In [14]:
class Sigmoid:
    def __init__(self):
        self.out = None
        
    def forward(self, x):
        out = 1/(1+np.exp(-x))
        self.out = out # 記憶しておく
        return out
    
    def backward(self, dout):
        """
        dout : float, 上流(出力)側の勾配
        """        
        dLdx = self.out*(1-self.out)*dout 
        return dLdx

In [15]:
sm = Sigmoid()

x = np.array([-10])
dout = np.array([3])
print("forward=", sm.forward(x))
dLdx = sm.backward(dout)
print("dLdx=", dLdx)
print()

x = np.array([0])
dout = np.array([3])
print("forward=", sm.forward(x))
dLdx = sm.backward(dout)
print("dLdx=", dLdx)
print()

x = np.array([10])
dout = np.array([3])
print("forward=", sm.forward(x))
dLdx = sm.backward(dout)
print("dLdx=", dLdx)

forward= [4.53978687e-05]
dLdx= [0.00013619]

forward= [0.5]
dLdx= [0.75]

forward= [0.9999546]
dLdx= [0.00013619]
